name: clock

dependencies:
  - base

library:
  exposed-modules: Clock
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - clock
      - hspec
