name: word-count

dependencies:
  - base
  - containers

library:
  exposed-modules: WordCount
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.
    - split

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - word-count
      - hspec
