name: pythagorean-triplet

dependencies:
  - base

library:
  exposed-modules: Triplet
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - pythagorean-triplet
      - hspec
