name: scrabble-score

dependencies:
  - base

library:
  exposed-modules: Scrabble
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.
    - containers

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - scrabble-score
      - hspec
